name: Terraform Destroy

on:
  push:
    branches:
      - '*.[dev|prod].destroy'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's/\.destroy$//')
          terraform workspace select $branch_name
          terraform destroy -auto-approve
        env:
          TF_VAR_some_variable: ${{ secrets.SOME_VARIABLE }}
