name: Terraform Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.x

      - name: Get Active Workspace
        id: workspace
        run: echo "::set-output name=workspace::$(terraform workspace show)"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: steps.workspace.outputs.workspace == 'dev'  # Solo aplica si el workspace es 'dev'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: steps.workspace.outputs.workspace == 'dev'  # Solo destruye si el workspace es 'dev'
        run: terraform destroy -auto-approve
